export const themeOptions = [
  { label: "Bootstrap4 Light Blue", value: "bootstrap4-light-blue" },
  { label: "Bootstrap4 Light Purple", value: "bootstrap4-light-purple" },
  { label: "Bootstrap4 Dark Blue", value: "bootstrap4-dark-blue" },
  { label: "Bootstrap4 Dark Purple", value: "bootstrap4-dark-purple" },
  { label: "MD Light Indigo", value: "md-light-indigo" },
  { label: "MD Light Deeppurple", value: "md-light-deeppurple" },
  { label: "MD Dark Indigo", value: "md-dark-indigo" },
  { label: "MD Dark Deeppurple", value: "md-dark-deeppurple" },
  { label: "MDC Light Indigo", value: "mdc-light-indigo" },
  { label: "MDC Light Deeppurple", value: "mdc-light-deeppurple" },
  { label: "MDC Dark Indigo", value: "mdc-dark-indigo" },
  { label: "MDC Dark Deeppurple", value: "mdc-dark-deeppurple" },
  { label: "Tailwind Light", value: "tailwind-light" },
  { label: "Fluent Light", value: "fluent-light" },
  { label: "Lara Light Blue", value: "lara-light-blue" },
  { label: "Lara Light Indigo", value: "lara-light-indigo" },
  { label: "Lara Light Purple", value: "lara-light-purple" },
  { label: "Lara Light Teal", value: "lara-light-teal" },
  { label: "Lara Dark Blue", value: "lara-dark-blue" },
  { label: "Lara Dark Indigo", value: "lara-dark-indigo" },
  { label: "Lara Dark Purple", value: "lara-dark-purple" },
  { label: "Lara Dark Teal", value: "lara-dark-teal" },
  { label: "Soho Light", value: "soho-light" },
  { label: "Soho Dark", value: "soho-dark" },
  { label: "Viva Light", value: "viva-light" },
  { label: "Viva Dark", value: "viva-dark" },
  { label: "Mira", value: "mira" },
  { label: "Nano", value: "nano" },
  { label: "Saga Blue", value: "saga-blue" },
  { label: "Saga Green", value: "saga-green" },
  { label: "Saga Orange", value: "saga-orange" },
  { label: "Saga Purple", value: "saga-purple" },
  { label: "Vela Blue", value: "vela-blue" },
  { label: "Vela Green", value: "vela-green" },
  { label: "Vela Orange", value: "vela-orange" },
  { label: "Vela Purple", value: "vela-purple" },
  { label: "Arya Blue", value: "arya-blue" },
  { label: "Arya Green", value: "arya-green" },
  { label: "Arya Orange", value: "arya-orange" },
  { label: "Arya Purple", value: "arya-purple" },
];


